apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.extraConfigMapEnvVars.SYNCHRONIZER_SCHEDULE }}"
  # How many completed jobs should be kept
  successfulJobsHistoryLimit: 1
  # We use concurrencyPolicy: Forbid to make sure that a new cronjob doesn't kill a previously started cronjob before it's completed
  # Here you can read about concurrencyPolicy: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#concurrency-policy
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}
          restartPolicy: OnFailure
          containers:
            - name: {{ .Release.Name }}
              # If we leave registry empty, then there will be an excess slash(/) in front of the repository, which will cause "InvalidImageName" error
              {{- if .Values.image.registry }}
              image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
              {{- else }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              {{- end }}
              resources:
                limits:
                  cpu: {{ .Values.resources.limits.cpu }}
                requests:
                  cpu: {{ .Values.resources.requests.cpu }}
                  memory: {{ .Values.resources.requests.memory }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
