image:
  registry: ghcr.io
  repository: tourmalinecore/pelican-env-synchronizer
  pullPolicy: Always

resources:
  limits:
    cpu: 200m
  requests:
    cpu: 1m
    memory: 256Mi

extraConfigMapEnvVars:
